site_name: PyManyObjective
site_description: A Framework for Inverse Modeling Applied to Multi-objective Evolutionary Algorithms
theme:
  name: material
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-4
        name: Trocar para tema escuro

    - scheme: slate
      toggle:
        icon: material/brightness-7
        name: Trocar para tema claro
nav: # Basta adicionar os markdowns e o nome da página da documentação
  - Home: index.md 
