[tool.pyright]
include = ["src"]
exclude = [
    "**/node_modules",
    "**/__pycache__",
    "**/venv",
    "./venv",
]


ignore = ["src/oldstuff"]
venvPath = "."
venv = "./venv"

reportMissingImports = true
reportMissingTypeStubs = false

executionEnvironments = [
  # { root = "src" }
]
